
language: php
php:
  - "5.4"
  - "5.3"

before_script:
  - wget http://getcomposer.org/composer.phar
  - chmod u+x ./composer.phar
  - ./composer.phar install --dev

#branches:
#  only:
#    - master

notifications:
  email:
    recipients:
      - flyingmana@googlemail.com
      - vinai@netzarbeiter.com
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#magento-composer"
    on_success: change # default: always
    on_failure: always # default: always
