
platform: 'x86'
clone_folder: C:\projects\random\customer\magento

install: 
  - cinst OpenSSL.Light
  - SET PATH=C:\Program Files\OpenSSL;%PATH%
  - cinst php 
  - cd c:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - SET PATH=C:\tools\php;%PATH%
  - cd C:\projects\random\customer\magento
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --prefer-dist --no-interaction --dev

test_script:
  - cd C:\projects\random\customer\magento
  - vendor\bin\phpunit.bat
